spring:
  application:
    name: aws-cloudwatch-microservice2

cloud:
  aws:
    stack:
      auto: false
    credentials:
      instance-profile: false
      use-default-aws-credentials-chain: true
    region:
      auto: false
      static: ${AWS_REGION:us-east-1}

management:
  metrics:
    enable:
      jvm: false
      logback: false
    tags:
      microservice: ${spring.application.name}
      region: ${AWS_REGION:us-east-1a}
    export:
      cloudwatch:
        enabled: true
        namespace: SpringActuatorMetrics
